<a href="/frontend">HOME</a>
<h2>List Orders</h2>
<table class='table table-dark table-striped rounded m-0'>
    <tr>
        <th>PRODUCT NAME</th>
        <th>PRICE</th>
        <th>STOCK</th>
        <th></th>
    </tr>
    <?php foreach ($products as $q) { ?>
        <tr>
            <td><?php echo $q['name'] ?></td>
            <td><?php echo $q['price'] ?></td>
            <td><?php echo $q['stock'] ?></td>
            <? if ($q['stock'] > 5) { ?>
                <td><a href="/frontend/product/buy/<?php echo $q['_id'] ?>" class='btn btn-primary'>BUY NOW</a></td>
            <? } else { ?>
                <td><span class='fw-bolder text-muted'>OUT OF STOCK</span></td>
            <? } ?>
        </tr>
    <?php } ?>
</table>