<div>
    <a href="/">Home</a>&nbsp;&nbsp;
</div>
<div class='mt-5'>
    <?php echo $message ?? "" ?>
</div>
<div class='container row gx-5 content-justify-center'>
    <div class='m-auto mt-5 p-3 col'>
        <form method="POST" class='form-group  border rounded bg-info text-dark p-3'>
            <h3>Create Webhook</h3>
            <input name="name" type="text" required placeholder="Webhook Name" class='form-control'><br>
            <select name="hook" class='form-select'>
                <?php foreach ($hooks as $k => $v) { ?>
                    <option value ="<?php echo $k?>"><?php echo $v?></option>
                <?php } ?>
            </select><br>
            <input name="url" type="text" required placeholder="Webhook URL" class='form-control'><br>
            <input name="key" type="password" placeholder="Secret key (optional)" class='form-control'><br>
            <input type='submit' value='Create' class='btn-dark text-light form-control'>
        </form>
    </div>
</div>