<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Auth</title>
    <link rel="stylesheet" href="/assets/main.css">
</head>

<body>
    <div>
        <h2>Authorize email</h2>
        <form class='form' method="post" action="/api/auth">
            <input type='hidden' name ='callback' value='<?echo $callback?>'>
            <input type="email" name="email" placeholder="Email">
            <input type="submit" value="generate token">
        </form>
    </div>
</body>

</html>