<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Auth</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body class='bg-dark text-light'>
    <div class='container mt-5'>
        <form class='form-group w-50 m-auto' method="post" action="/api/auth">
            <h2>Permission Required</h2>
            <input type='hidden' name='callback' value='<? echo $callback ?>'>
            <div class='form-floating mb-2'>
                <input type="email" value="<?php echo $email ?>" class='form-control bg-dark border-secondary text-light' name="email" placeholder="Email">
                <label>Email</label>
            </div>
            <input type="submit" class='form-control btn-success' value="Allow">
        </form>
    </div>
</body>

</html>