<div>
    <a href="/app/">User Login</a>&nbsp;&nbsp;
</div>
<div class='mt-5'>
    <?php echo $message ?? "" ?>
</div>
<div class='container row gx-5 content-justify-center'>
    <div class='m-auto mt-5 p-3 col'>
        <form method="POST" class='form-group  border rounded bg-success text-light p-3'>
            <h3>Admin Login</h3>
            <input type="hidden" value="login" name='action'>
            <input name="email" type="email" placeholder="email" class='form-control'><br>
            <input name="password" type="password" placeholder="password" class='form-control'><br>
            <input type='submit' value='Login' class='btn-dark text-light form-control'>
        </form>
    </div>
    <div class='m-auto mt-5 p-3 col'>
        <form method="POST" class='form-group  border rounded p-3 bg-dark text-warning'>
            <h3>Admin Signup</h3>
            <input type="hidden" value="signup" name='action'>
            <input name="email" type="email" placeholder="email" class='form-control'><br>
            <input name="password" type="password" placeholder="password" class='form-control'><br>
            <input type='submit' value='Signup' class='btn-warning form-control'>
        </form>
    </div>
</div>