<h2>List Orders</h2>
<table class='table table-dark table-striped'>
    <tr>
        <th>USER EMAIL</th>
        <th>PRODUCT ID</th>
        <th>PRODUCT QUANTITY</th>
        <th>STATUS</th>
    </tr>
    <?php foreach($orders as $q){ ?>
        <tr>
            <td><?php echo $q['email'] ?></td>
            <td><?php echo $q['product_id'] ?></td>
            <td><?php echo $q['qty'] ?></td>
            <td><?php echo $q['status'] ?></td>
        </tr>
    <?php } ?>
</table>