<a href="/app/index/listorders">List Orders</a>
<div class="row">
<div class='col float-end'>
    </div>
    <div class="col-2">
        <?

        echo $this->tag->linkTo([
            "/app/index/newproduct",
            "Add Product",
            "class" => 'btn btn-danger'
        ]);

        ?>
    </div>
    
</div>
<div class='mt-1 rounded-3 overflow-hidden p-0 border border-dark'>
    <table class='table table-striped table-dark text-center m-0'>
        <tr>
            <th>Name</th>
            <th>Price</th>
            <th>STOCK</th>
            <th></th>
        </tr>
        <? foreach ($products as $v) : ?>
            <tr>
                <td><? echo $v['name'] ?></td>
                <td><? echo $v['price'] ?></td>
                <td><? echo $v['stock'] ?></td>
                <td>
                    <a href='/app/index/newproduct/<? echo $v['_id']['$oid'] ?>' class='text-warning fw-bold'>EDIT</a>
                </td>
            </tr>
        <? endforeach ?>
    </table>
</div>