<div class='container-fluid mt-2'>
    <form method="POST" class='form-group'>
        <input type='text' class='form-control' value='<?php echo $product['name']?>' name="name" placeholder="name" >
        <input type='number' class='form-control' value='<?php echo $product['price']?>' placeholder="price" name="price">
        <input type='number' class='form-control' value='<?php echo $product['stock']?>' placeholder="stock" name="stock">
        <input type="submit" class='form-control btn-info'>
    </form>
</div>